apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: db
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data/tp-kube/database"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: db

spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
