services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: fischer1956
      POSTGRES_USER: postgres
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/

  api:
    build:
      context: api
      target: prod
    restart: always
    environment:
      CITY_API_ADDR: 0.0.0.0
      CITY_API_PORT: 2022
      CITY_API_DB_URL: postgres://postgres:fischer1956@db:5432/?sslmode=disable
      CITY_API_DB_USER: postgres
    ports:
      - "2022:2022"
    depends_on:
      - db
    networks:
      - default

  webapp:
    build:
      context: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
