apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api

spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ghcr.io/do3-2023/thomas-kube-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2022
        env:
        - name: CITY_API_ADDR
          value: "localhost"
        - name: CITY_API_PORT
          value: "2022"
        - name: CITY_API_DB_URL
          value: "postgres://postgres:fischer1956@database.db.svc.cluster.local/?sslmode=disable"
        - name: CITY_API_DB_USER
          value: "postgres"
