spin_manifest_version = 2

[application]
name = "http-go"
version = "0.1.0"
authors = ["Mauran <thomas.mauran@etu.umontpellier.fr>"]
description = ""

[[trigger.http]]
route = "/..."
component = "http-go"

[component.http-go]
source = "main.wasm"
allowed_outbound_hosts = []
[component.http-go.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
