apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  strategy: {}
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: ghcr.io/do3-2023/thomas-kube-web:latest
        name: thomas-kube-frontend
        resources:
          limits: {}
          requests:
            memory: 500Mi
            cpu: 250m
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 5

        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 2
      initContainers:
      - name: init-api
        image: busybox
        command: ['sh', '-c', 'until nc -zv backend-service.backend.svc.cluster.local 2022; do echo waiting for API; sleep 1; done;']
status: {}
