apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: frontend

spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30080
  type: NodePort
