spin_manifest_version = 2

[application]
name = "wasm-api"
version = "0.1.0"
authors = ["Mauran <thomas.mauran@etu.umontpellier.fr>"]
description = "wasm person api in go"

[[trigger.http]]
route = "/..."
component = "wasm-api"

[variables]
db_url = { required = true }

[component.wasm-api]
source = "main.wasm"
allowed_outbound_hosts = ["*://0.0.0.0:5432"]

[component.wasm-api.variables]
db_url = "0.0.0.0"
db_username = "postgres"
db_password = "fischer1956"
db_name = "postgres"

[component.wasm-api.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
