name: Main workflow (check & build push docker)

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  lint-city:
    name: City linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    ## Golang linter
    ##
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: false

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.53
        working-directory: ./thomas-kube

  build-and-push-images:
    name: Build and publish image city-api to ghcr.io
    runs-on: ubuntu-latest
    needs:
    - lint-city
    permissions:
      packages: write
    outputs:
      version: ${{ steps.meta.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    ## Authenticate to registry repo github
    ##
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    ## Build and push Docker image
    ##
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}
        tags: type=sha

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ env.DOCKERFILE_CONTEXT }}
        target: ${{ env.DOCKERFILE_TARGET }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
